### ISSUE TITLE
[BUG] Response errors

### ISSUE THREAD

**Issue by mishop** [kitabisa/mubeng#163]
**I have two response errors**
`` context deadline exceeded (Client.Timeout exceeded while awaiting headers) ``

Second error:

```http: panic serving someip:58529: runtime error: invalid memory address or nil pointer dereference
goroutine 389 [running]:
net/http.(*conn).serve.func1(0xc000153040)
        /usr/lib/go-1.15/src/net/http/server.go:1801 +0x147
panic(0x94f400, 0xdb46d0)
        /usr/lib/go-1.15/src/runtime/panic.go:975 +0x47a
ktbs.dev/mubeng/internal/server.(*Proxy).onRequest(0xc000199f90, 0xc00018d600, 0xc000405980, 0x0, 0x0)
        /home/misho/mubeng/internal/server/handler.go:83 +0x34a
github.com/elazarl/goproxy.FuncReqHandler.Handle(0xc000199fa0, 0xc00018d600, 0xc000405980, 0x10, 0x10)
        /home/misho/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/actions.go:19 +0x3a
github.com/elazarl/goproxy.(*ReqProxyConds).Do.func1(0xc00018d600, 0xc000405980, 0xc000045400, 0x0)
        /home/misho/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/dispatcher.go:216 +0xcd
github.com/elazarl/goproxy.FuncReqHandler.Handle(0xc0001a3780, 0xc00018d600, 0xc000405980, 0x40cbbb, 0x10)
        /home/misho/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/actions.go:19 +0x3a
github.com/elazarl/goproxy.(*ProxyHttpServer).filterRequest(0xc000152320, 0xc00018d600, 0xc000405980, 0xc0003afb90, 0x4)
        /home/misho/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/proxy.go:62 +0x74
github.com/elazarl/goproxy.(*ProxyHttpServer).ServeHTTP(0xc000152320, 0xaa5f60, 0xc00016a700, 0xc00018d600)
        /home/misho/go/pkg/mod/github.com/elazarl/goproxy@v0.0.0-20210110162100-a92cc753f88e/proxy.go:124 +0x305
net/http.serverHandler.ServeHTTP(0xc00009a540, 0xaa5f60, 0xc00016a700, 0xc00018d600)
        /usr/lib/go-1.15/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000153040, 0xaa70e0, 0xc000063880)
        /usr/lib/go-1.15/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/lib/go-1.15/src/net/http/server.go:2969 +0x36c
```

I'm trying using this with colly but not working.
Thx

**Comment by dwisiswant0** [comment]
What version do you use, @mishop?

**Comment by mishop** [comment]
v0.9.5

**Comment by dwisiswant0** [comment]
Give me more context: How do you run mubeng? What are the flags consumed?

**Comment by mishop** [comment]
`` mubeng -a ip:8088 -f live.txt -m random ``

**Comment by dwisiswant0** [comment]
It's because your proxy isn't fresh.
